import re
from pathlib import Path
from collections import Counter

INPUT = Path("/workspaces/3056AIFall2025/GCAP3056_Fall_2025/teacherNotes/Chronic-Care/DiscussionNotes")
OUTPUT_DIR = Path("/workspaces/3056AIFall2025/GCAP3056_Fall_2025/demo/lab0/output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_FILE = OUTPUT_DIR / "summary.md"

EXTS = {".md", ".markdown", ".txt"}

STOPWORDS = {
    "the","and","for","that","with","this","from","are","was","were","have","has","had",
    "not","but","you","your","they","their","them","our","we","a","an","in","on","of","to",
    "is","it","as","by","be","or","at","can","will","may"
}

def split_sentences(text):
    parts = re.split(r'(?<=[\.\?\!])\s+', text.strip())
    return [p.strip() for p in parts if p.strip()]

def extract_title(text, path):
    m = re.search(r'^\s*#\s+(.+)$', text, flags=re.MULTILINE)
    if m:
        return m.group(1).strip()
    return path.stem

def top_keywords(text, n=8):
    words = re.findall(r'\w+', text.lower())
    words = [w for w in words if w not in STOPWORDS and len(w) > 2 and not w.isdigit()]
    return [w for w, _ in Counter(words).most_common(n)]

def summarize_file(path):
    text = path.read_text(encoding="utf-8", errors="ignore")
    title = extract_title(text, path)
    sents = split_sentences(text)
    snippet = " ".join(sents[:2]) if sents else ""
    keywords = top_keywords(text, 6)
    return {"path": path.name, "title": title, "snippet": snippet, "keywords": keywords, "full": text}

def main():
    files = sorted(p for p in INPUT.iterdir() if p.is_file() and p.suffix.lower() in EXTS)
    results = [summarize_file(p) for p in files]

    all_text = "\n".join(r["full"] for r in results)
    overall_keywords = top_keywords(all_text, 12)

    lines = []
    lines.append("# Summary of DiscussionNotes")
    lines.append("")
    lines.append(f"- Input folder: `{INPUT}`")
    lines.append(f"- Files processed: {len(results)}")
    lines.append("")
    lines.append("## Key themes / keywords")
    if overall_keywords:
        lines.append(", ".join(f"`{k}`" for k in overall_keywords))
    else:
        lines.append("_No prominent keywords found._")
    lines.append("")
    lines.append("## Per-file summaries")
    for r in results:
        lines.append(f"### {r['title']}  ")
        lines.append(f"- filename: `{r['path']}`")
        if r["snippet"]:
            lines.append(f"- excerpt: {r['snippet']}")
        if r["keywords"]:
            lines.append(f"- keywords: {', '.join(r['keywords'])}")
        lines.append("")

    lines.append("---")
    lines.append("Generated by script: generate_summary.py")

    OUT_FILE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote summary to: {OUT_FILE}")

if __name__ == "__main__":
    main()